services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80'    # Public HTTP Port
      - '443:443'  # Public HTTPS Port
      - '81:81'    # Admin Web Port
    environment:
      DISABLE_IPV6: 'true'  # Commonly needed on many systems
      TZ: Asia/Kolkata    # Ensures correct timestamps
    volumes:
      - npm-data:/data
      - letsencrypt-data:/etc/letsencrypt
    networks:
      - npm-network

networks:
  npm-network:
    name: npm-network
    external: true

volumes:
  npm-data:
  letsencrypt-data:
